#include "stdafx.h"
#include "OptmizeFunc.h"
#include <cmath>
#include <cstdlib>
#include "CalcuFunc.h"
#include <string>


//选出合适的山脊，避免前排沟 作n 个选择集  输出acgepoint2dary
//参数：A点 （横洞PL 斜井PL）输出所有可能山脊位置，考虑角度，
//隧道点列，考虑隧道上方岩层厚度 


bool OptmizeFunc::Vallay()
{

	AcGeLineSeg3d acGeLineSegtmp1(AcGePoint3d(0, 100, 0), AcGePoint3d(50, 100, 0));
	AcGeLineSeg3d acGeLineSegtmp2(AcGePoint3d(-50, 50, 0), AcGePoint3d(-50, 120, 0));
	AcGeTol gGetol; gGetol.setEqualPoint(0.001);//设置精度
	AcGePoint3d intPnt;//交点
	bool bRec = acGeLineSegtmp1.intersectWith(acGeLineSegtmp2, intPnt, gGetol);//交点
	return false;
}

bool OptmizeFunc::Ridge(AcGePoint2dArray& RidgePtAry, AcGePoint2d& TunAPt,
	AcDbObjectIdArray HD, AcDbObjectIdArray XJ)
{
	return false;
}

bool OptmizeFunc::PolyToGeCurve(const AcDbPolyline*& pPline, AcGeCurve2d*& pGeCurve)
{
	int nSegs; // number of segment
	AcGeLineSeg2d line, * pLine; // 几何曲线的直线段部分
	AcGeCircArc2d arc, * pArc; // 几何曲线的圆弧部分
	AcGeVoidPointerArray geCurves; // 指向组成几何曲线各分段的指针数组
	nSegs = pPline->numVerts() - 1;

	for (int i = 0; i < nSegs; i++)
	{
		if (pPline->segType(i) == AcDbPolyline::kLine)
		{
			pPline->getLineSegAt(i, line);
			pLine = new AcGeLineSeg2d(line);
			geCurves.append(pLine);
		}
		else if (pPline->segType(i) == AcDbPolyline::kArc)
		{
			pPline->getArcSegAt(i, arc);
			pArc = new AcGeCircArc2d(arc);
			geCurves.append(pArc);
		}
	}
	if (pPline->isClosed() && pPline->segType(nSegs) ==
		AcDbPolyline::kArc)
	{
		pPline->getArcSegAt(nSegs, arc);
		pArc = new AcGeCircArc2d(arc);
		pArc->setAngles(arc.startAng(), arc.endAng() -
			(arc.endAng() - arc.startAng()) / 100);
		geCurves.append(pArc);
	}
	if (geCurves.length() == 1)
	{
		pGeCurve = (AcGeCurve2d*)geCurves[0];
	}
	else
	{
		pGeCurve = new AcGeCompositeCurve2d(geCurves);
	}
	if (geCurves.length() > 1)
	{
		for (int i = 0; i < geCurves.length(); i++)
		{
			delete geCurves[i];
		}
	}

	return true;
}
//斜井选取
bool OptmizeFunc::SlopeNLength(AcDbObjectIdArray& XJPLIdAry, AcGePoint3d Apt)
{
	return false;
}



bool OptmizeFunc::NearRdPl(AcGePoint2d& BPt, AcDbObjectId RdLayId)
{
	ads_name SSname; struct resbuf* PointList;
	AcGePoint2dArray SSPL; AcGePoint2d SSpt; int i, rt;
	AcDbEntity* pRoad;
	for (i = 0; i < 4; i++)
	{
		SSpt.x = BPt.x + cos(i * pi) * 700;
		SSpt.y = BPt.y + sin(i * pi) * 700;
	}
	PointList = acutBuildList(RTPOINT, SSPL[0], RTPOINT, SSPL[1],
		RTPOINT, SSPL[2], RTPOINT, SSPL[3], RTNONE);
	rt = acedSSGet(_T("CP"), PointList, NULL, NULL, SSname);
	if (rt != RTNORM)
	{
		acedAlert(_T("\n unknown error!"));
		return false;
	}
	Adesk::Int32 length; Acad::ErrorStatus es;
	acedSSLength(SSname, &length);
	acutPrintf(_T("\n选择集个数：%d"), length);
	for (i = 0; i < length; i++)
	{
		ads_name ent;
		acedSSName(SSname, i, ent);
		AcDbObjectId objId;
		acdbGetObjectId(objId, ent);

		es = acdbOpenAcDbEntity(pRoad, objId,
			AcDb::kForRead);
		if (es == Acad::eWasOpenForWrite) { continue; }
		if (pRoad->layerId() == RdLayId) { return true; }
	}

	return false;
}

bool OptmizeFunc::TunmileTxtSSget(AcGePoint2d& Point2d, AcString MileAcString)
{
	ads_name SSname; struct resbuf* PointList;
	AcGePoint2dArray SSPL; AcGePoint2d SSpt; int i, rt;
	AcDbEntity* pLiCHengTxt;
	for (i = 0; i < 10; i++)
	{
		SSpt.x = Point2d.x + cos(i * pi / 5) * 45;
		SSpt.y = Point2d.y + sin(i * pi / 5) * 45;
		SSPL.append(SSpt);
	}//设置端点附近45米范围有里程标识
	PointList = acutBuildList(RTPOINT, SSPL[0], RTPOINT, SSPL[1]
		, RTPOINT, SSPL[2], RTPOINT, SSPL[3], RTPOINT, SSPL[4], RTPOINT, SSPL[5]
		, RTPOINT, SSPL[6], RTPOINT, SSPL[7], RTPOINT, SSPL[8], RTPOINT, SSPL[9]
		, RTNONE);
	rt = acedSSGet(_T("CP"), PointList, NULL, NULL, SSname);
	if (rt != RTNORM)
	{
		acedAlert(_T("\n Selction set error!"));
		pLiCHengTxt->close();
		return false;
	}
	Adesk::Int32 length; Acad::ErrorStatus es;
	
	const ACHAR* DK = _T("DK");
	acedSSLength(SSname, &length);
	acutPrintf(_T("\n选择集个数：%d"), length);
	for (i = 0; i < length; i++)
	{
		ads_name ent;
		acedSSName(SSname, i, ent);
		AcDbObjectId objId;
		acdbGetObjectId(objId, ent);
		es = acdbOpenAcDbEntity(pLiCHengTxt, objId,
			AcDb::kForRead);
		if (es == Acad::eWasOpenForWrite) { continue; }
		if (pLiCHengTxt->isKindOf(AcDbText::desc()) == Adesk::kTrue)
		{
			AcDbText* mileTxt = AcDbText::cast(pLiCHengTxt);
			mileTxt->textString(MileAcString);
			if (MileAcString.find(DK) != -1)
			{
				return true;
			}
		}
		else if (pLiCHengTxt->isKindOf(AcDbMText::desc()) == Adesk::kTrue)
		{
			AcDbMText* MileMtext = AcDbMText::cast(pLiCHengTxt);
			MileMtext->text(MileAcString);
			if (MileAcString.find(DK) != -1)
			{
				return true;
			}
		}
	}
	acedAlert(_T("\n cannot find DK*,\nplz move text"));
	pLiCHengTxt->close();
	return false;
}

//较后的约束，用于判断目标辅道与隧道夹角，确定辅道是否转向
bool OptmizeFunc::AngBetweenAtNMt(AcGePoint2d APt, AcGePoint2d BPt, AcGePoint2dArray TunAPtAry, int num)
{
	double a1, a2, b1, b2, AB, cosA1, cosA2;
	AB = APt.distanceTo(BPt);
	a1 = BPt.distanceTo(TunAPtAry[num + 1]);//a1=bc
	a2 = BPt.distanceTo(TunAPtAry[num - 1]);//a2=bd
	b1 = APt.distanceTo(TunAPtAry[num + 1]);//b1=ac
	b2 = APt.distanceTo(TunAPtAry[num - 1]);//b2=ad
	cosA1 = (AB * AB + b1 * b1 - a1 * a1) / (2 * b1 * AB);
	cosA2 = (AB * AB + b2 * b2 - a2 * a2) / (2 * b2 * AB);
	if (fabs(cosA1) < 0.866 && fabs(cosA2) < 0.866) { return true; }
	else { return false; }
}

bool OptmizeFunc::Spacialearth(AcGePoint2d Apt, AcGePoint2d Bpt, AcDbObjectId SpErthLay)
{

	return false;
}

bool OptmizeFunc::Spacialearth(AcGePoint2d Apt, AcGePoint2d Bpt, AcGePoint2d Cpt, AcDbObjectId SpErthLay)
{
	return false;
}

//计算隧道上方岩层厚度 避免前排沟
bool OptmizeFunc::SSGtoAvgH(AcGePoint2d Pt, double& elevation, double r)
{
	int i, k, rt, plNum = 0; double SUM = 0;
	AcGePoint2d SSpt;
	ads_name SSName;
	AcGePoint2dArray PLPtAry;
	struct resbuf* PointList;
	for (k = 0; k < 4; k++)
	{
		SSpt.x = Pt.x + cos(k * pi / 2) * r * 1.414;
		SSpt.y = Pt.y + sin(k * pi / 2) * r * 1.414;
		PLPtAry.append(SSpt);
	}
	PointList = acutBuildList(RTPOINT, PLPtAry[0], RTPOINT, PLPtAry[1],
		RTPOINT, PLPtAry[2], RTPOINT, PLPtAry[3], RTNONE);
	AcDbEntity* pEnt;
	Acad::ErrorStatus es;
	rt = acedSSGet(_T("CP"), PointList, NULL, NULL, SSName);
	if (rt != RTNORM)
	{
		acedAlert(_T("\n unknown error!"));
		acutPrintf(_T("\n Selection Set error."));
		return false;
	}
	Adesk::Int32 length;
	acedSSLength(SSName, &length);

	for (i = 0; i < length; i++)
	{
		ads_name ent;
		acedSSName(SSName, i, ent);
		AcDbObjectId objId;
		acdbGetObjectId(objId, ent);
		es = acdbOpenAcDbEntity(pEnt, objId,
			AcDb::kForRead);
		if (es == Acad::eWasOpenForWrite) { continue; }
		if (pEnt->isKindOf(AcDbPolyline::desc()) == Adesk::kTrue)
		{
			plNum++;
			SUM = SUM + pEnt->database()->elevation();
		}
	}
	if (plNum == 0) { return false; }
	elevation = SUM / plNum;

	acutRelRb(PointList);
	acedSSFree(SSName);
	return true;
}

bool OptmizeFunc::PLLength(AcDbPolyline* pPL, double& TolLen)
{
	AcGePoint2d Pt, PtNt;
	AcGeCircArc2d arc, * pArc;
	AcGeLineSeg2d line, * pLine;
	double length = 0.0; int nSegs;
	nSegs = pPL->numVerts();
	/*for (i = 0; i < pPL->numVerts() - 1; i++)
	{
		pPL->getPointAt(i, Pt);
		pPL->getPointAt(i + 1, PtNt);
		length = length + Pt.distanceTo(PtNt);
	}
	TolLen = length;*/
	for (int i = 0; i < nSegs; i++)
	{
		if (pPL->segType(i) == AcDbPolyline::kLine)
		{
			pPL->getLineSegAt(i, line);
			pLine = new AcGeLineSeg2d(line);
			length = length + pLine->length();
		}
		else if (pPL->segType(i) == AcDbPolyline::kArc)
		{
			pPL->getArcSegAt(i, arc);
			pArc = new AcGeCircArc2d(arc);
			length = length + (pArc->radius() *
				(abs(pArc->endAng() - pArc->startAng()))
				);
			//* pi / 180);
		}
	}
	TolLen = length;
	return true;
}

//标记图层dz
bool OptmizeFunc::TnlDataBase(const ACHAR* FileN)
{
	AcDbDatabase* pDb = new AcDbDatabase(Adesk::kFalse);
	pDb->readDwgFile(FileN);
	AcDbBlockTable* pBlTbl;
	pDb->getSymbolTable(pBlTbl, AcDb::kForRead);
	AcDbBlockTableRecord* pBlkRec;
	pBlTbl->getAt(ACDB_MODEL_SPACE, pBlkRec, AcDb::kForWrite);
	pBlTbl->close();
	AcDbBlockTableRecordIterator* pBlkTblRcdIter;
	pBlkRec->newIterator(pBlkTblRcdIter);
	int i = 0;


	AcGePoint2d& pt = AcGePoint2d();
	//AcDbExtents *pExt;
	for (pBlkTblRcdIter->start(); !pBlkTblRcdIter->done(); pBlkTblRcdIter->step())
	{

	}
	pBlkRec->close();
	delete pBlkTblRcdIter;
	delete pDb;
	return true;
	return false;
}

	//acstring DK309+590 DK297+190 对应高程 760.xx 1004.xx 
	//斜率 int 20 总长 int 12600,地质 objectidArray?
bool OptmizeFunc::ChooseExTlDb(AcString& DK1, AcString& DK2, double& Elevation1
	, double& elvation2, int& slope, int& Lenth, AcDbObjectIdArray DiZhiIdAry)
{
	// NOTE:
	//// 提示用户选择图形文件
	//AcDbLayerTable* pLay;
	//acdbHostApplicationServices()->workingDatabase()->getSymbolTable(pLay, AcDb::kForRead);
	//AcDbObjectId ChartInfoLayId, DZLayId, EditLID;//等高线ID...
	//pLay->getAt(_T("3"), ChartInfoLayId);// 表格名称x坐标确定选择数据
	//pLay->getAt(_T("地质"), DZLayId);//地质 和 长度 共用一个层名
	//pLay->getAt(_T("编辑"), EditLID);// 总长 图层：编辑  内轨顶面设计高程 设计坡度（‰）
	//当前数据库图层Id不能匹配外部数据库
	//AcDbText* DKText;
	// 第一次循环提取信息锚点
	// position acdbtext左下角坐标 alignmentPoint 文字对齐坐标，如果没有设置则为0点
	//AcGePoint3d postion, alnPoint;
	//AcDbObjectIdArray infoIdAry;
		//if (pEnt->layerId() == ChartInfoLayId  
		// 由于数据库的不稳定性，不宜用layerID函数读取外部数据库
		// 可选择方式有，layerFilter,openpartialDB 
		// 或者用AcString 转换成 ACHAR*识别图层是有效的
		// abc = acutAcStringToAChar(AcString, errorStatus);
		//  pText->layer(layerb);
		// if ( pEnt->layer() == _T("编辑") || 
		//	layerb == _T("编辑"))
		//
		// postion = pText->position();
		// alnPoint = pText->alignmentPoint();
		// 文字的两个坐标函数没问题
		// 
		//textstringconst()函数没有terminal sign（\0）
		// 不能放在判断语句里
		// 对于Text 或MText
		// 文字类函数推荐使用带有AcString& 参数类型
		//textString()函数不推荐
		// this function is deprecated,please use another overload
		// 也用不了（for unknown reason），需换用另一个重载函数
		// 可用textstring（AcString）识别
		//
	int n = atoi("123");
	acutPrintf(_T("\nn=%d"), n);
	//AcDbDatabase* pExternalDb(Adesk::kFalse);
	AcDbDatabase* pExternalDb = new AcDbDatabase(Adesk::kFalse);
	struct resbuf* rb;
	Acad::ErrorStatus IterSeekRt;
	rb = acutNewRb(RTSTR);
	if (RTNORM != acedGetFileD(_T("选择图形文件名称"), NULL, _T("dwg"), 0, rb))
	{
		acutRelRb(rb); return false;
	}
	if (Acad::eOk != pExternalDb->readDwgFile(rb->resval.rstring))
	{
		acedAlert(_T("读取DWG文件失败!")); acutRelRb(rb); return false;
	}
	acutRelRb(rb);
	//bool bRet = OpenExDbinSpacLay(pExternalDb, _T("编辑"));
	bool bRet = PartialOpenDatabase(pExternalDb);
	AcDbBlockTable* pBlkTbl01;
	pExternalDb->getSymbolTable(pBlkTbl01, AcDb::kForRead);
	AcDbBlockTableRecord* pBlkTblRcd1;
	pBlkTbl01->getAt(ACDB_MODEL_SPACE, pBlkTblRcd1, AcDb::kForRead);
	pBlkTbl01->close();
	AcDbBlockTableRecordIterator* pBlkTblRcdItr1;
	pBlkTblRcd1->newIterator(pBlkTblRcdItr1);
	AcDbEntity* pSectionEntity;
	//AcString = wString
	AcString SDText, ZongChang, layBianji, PoDuAcString, PoduChangDu;
	Acad::ErrorStatus es = eOk;
	double WeiLan_y = 0, ChangDu_y = 0, ZhongChangy = 0
		, LiCHeng_y = 0, Sheji_y = 0, SheJi_h = 0, DKText_y = 0
		, DKPlusTxt_y = 0, SlopeTxt_y = 0, SlopeLen_y = 0; //设计坡度按千分比计算
	int64_t PoDu, PoDu_Len, i64t = 0;
	for (pBlkTblRcdItr1->start(); !pBlkTblRcdItr1->done(); pBlkTblRcdItr1->step())
	{

		pBlkTblRcdItr1->getEntity(pSectionEntity, AcDb::kForRead);
		if (pSectionEntity->isKindOf(AcDbText::desc()) == Adesk::kTrue)
		{
			AcDbText* pText = AcDbText::cast(pSectionEntity);
			pText->textString(SDText);
			if (SDText == _T("围岩级别"))
			{
				WeiLan_y = pText->alignmentPoint().y;
			}
			else if (SDText == _T("总  长（m）"))
			{
				ZhongChangy = pText->alignmentPoint().y;
				acutPrintf(_T("\npostion:x = %f y=%f\nalignment:x = %f,y = %f"),
					pText->position().x, pText->position().y,
					pText->alignmentPoint().x, pText->alignmentPoint().y);
			}
			else if (SDText == _T("设计坡度（‰）"))
			{
				AcDbText* pPoDutxt;
				Sheji_y = pText->alignmentPoint().y;
				SheJi_h = pText->height();// y+-3/4h坡度文字y轴坐标
				for (pBlkTblRcdItr1->start(); !pBlkTblRcdItr1->done(); pBlkTblRcdItr1->step())
				{
					if ((pSectionEntity->colorIndex() == 6)
						&& pSectionEntity->isKindOf(AcDbText::desc()))
					{
						pPoDutxt = AcDbText::cast(pSectionEntity);
						SlopeTxt_y = pPoDutxt->alignmentPoint().y;
						if ((SlopeTxt_y > (Sheji_y - SheJi_h * 0.75))
							&& (SlopeTxt_y < (Sheji_y + SheJi_h * 0.75)))
							//此时pPoDutext是坡度或者长度
						{
							pPoDutxt->textString(PoDuAcString);
							i64t = PoDuAcString.asDeci64();
							if (i64t > 0 && i64t < 1000)
							{
								PoDu = i64t;
							}
							else if (i64t > 1000)
							{
								PoDu_Len = i64t;
							}
						}
					}
					else if (pSectionEntity->colorIndex() == 1)
					{

					}
				}

				IterSeekRt = pBlkTblRcdItr1->seek(pSectionEntity);
				if (IterSeekRt != Acad::eOk)
				{
					acedAlert(_T("迭代器定位失败"));
					pText->close();
					return false;
				}
			}
			else if (SDText == _T("里  程"))
			{
				LiCHeng_y = pText->alignmentPoint().y;
				AcDbText* pDKtext;
				for (pBlkTblRcdItr1->start(); !pBlkTblRcdItr1->done(); pBlkTblRcdItr1->step())
				{
					pBlkTblRcdItr1->getEntity(pSectionEntity, AcDb::kForRead);
					if ((pSectionEntity->colorIndex() == 6)
						&& pSectionEntity->isKindOf(AcDbText::desc()))
					{
						pDKtext = AcDbText::cast(pSectionEntity);
						DKText_y = pDKtext->alignmentPoint().y;
						if (DKText_y == LiCHeng_y)
						{

						}
					}
				}
				pDKtext->close();
				IterSeekRt = pBlkTblRcdItr1->seek(pText);
				if (IterSeekRt != Acad::eOk)
				{
					acedAlert(_T("迭代器定位失败"));
					pText->close();
					return false;
				}

			}
			pText->close();

		}
		else if (pSectionEntity->isKindOf(AcDbMText::desc()) == Adesk::kTrue)
		{
			//AcDbMText* pMText = AcDbMText::cast(pSectionEntity);
			//pMText->text(SDText);
			//if (SDText == _T("围岩级别"))
			//{
			//	acutPrintf(_T("\nMtext:%s,LAYER:%s\nlocation:x=%d,y=%d"),
			//		pMText->text(), pMText->layer(), pMText->location());
			//}
			//else if (SDText == _T("长  度（m）"))
			//{
			//}
			//else if (SDText == _T("总  长（m）"))
			//{
			//	acutPrintf(_T("\nMtext:%s,\nlocation:x=%d,y=%d"),
			//		pMText->text(), pMText->location());
			//}
		}


	}

	pSectionEntity->close();
	pBlkTblRcd1->close();
	delete pBlkTblRcdItr1;
	delete pExternalDb;
	return true;
}









//private:
// 
//partialopenfilter 需要在readDWGfile()后和closeInput()前使用
bool OptmizeFunc::PartialOpenDatabase(AcDbDatabase* pDb)
{
	if (pDb == NULL)
		return false;
	// 指定限制窗口的两个角点
	ads_point pt1, pt2;
	pt1[X] = SectionDiaGramScaleXMin;
	pt1[Y] = SectionDiaGramScaleYMin;
	pt1[Z] = 0.0;
	pt2[X] = SectionDiaGramScaleXMax;
	pt2[Y] = SectionDiaGramScaleYMax;
	pt2[Z] = 0.0;

	// 获得当前视图的方向
	AcGeVector3d normal; // 视图法线方向
	struct resbuf rb;
	acedGetVar(_T("VIEWDIR"), &rb);
	normal[0] = rb.resval.rpoint[0];
	normal[1] = rb.resval.rpoint[1];
	normal[2] = rb.resval.rpoint[2];
	normal.normalize();
	// 将窗口角点从WCS转换到ECS
	struct resbuf rbFrom, rbTo;
	rbFrom.restype = RTSHORT;
	rbFrom.resval.rint = 0; // WCS 
	rbTo.restype = RT3DPOINT;
	rbTo.resval.rpoint[0] = normal[0];
	rbTo.resval.rpoint[1] = normal[1];
	rbTo.resval.rpoint[2] = normal[2];
	acedTrans(pt1, &rbFrom, &rbTo, FALSE, pt1);
	acedTrans(pt2, &rbFrom, &rbTo, FALSE, pt2);
	// 创建空间过滤器
	AcGePoint2dArray array;
	array.append(AcGePoint2d(pt1[0], pt1[1]));
	array.append(AcGePoint2d(pt2[0], pt2[1]));
	AcDbSpatialFilter spatialFilter;
	spatialFilter.setDefinition(
		array,
		normal,
		pt1[Z],
		ACDB_INFINITE_XCLIP_DEPTH,
		-ACDB_INFINITE_XCLIP_DEPTH,
		Adesk::kTrue);
	// 创建图层过滤器
	AcDbLayerFilter layerFilter;
	layerFilter.add(_T("地质"));
	layerFilter.add(_T("编辑"));
	layerFilter.add(_T("3"));
	layerFilter.add(_T("GiCAD_PouMian"));

	// 对图形数据库应用局部加载
	Acad::ErrorStatus es;
	es = pDb->applyPartialOpenFilters(&spatialFilter, &layerFilter);

	if ((es == Acad::eOk) && pDb->isPartiallyOpened())
	{
		pDb->closeInput(true);
		return true;
	}
	else { return false; }
}

bool OptmizeFunc::OpenExDbinSpacLay(AcDbDatabase* pDb, const ACHAR* LayId)
{
	if (pDb == NULL)
		return false;
	// 指定限制窗口的两个角点
	ads_point pt1, pt2;
	pt1[X] = SectionDiaGramScaleXMin;
	pt1[Y] = SectionDiaGramScaleYMin;
	pt1[Z] = 0.0;
	pt2[X] = SectionDiaGramScaleXMax;
	pt2[Y] = SectionDiaGramScaleYMax;
	pt2[Z] = 0.0;

	// 获得当前视图的方向
	AcGeVector3d normal; // 视图法线方向
	struct resbuf rb;
	acedGetVar(_T("VIEWDIR"), &rb);
	normal[0] = rb.resval.rpoint[0];
	normal[1] = rb.resval.rpoint[1];
	normal[2] = rb.resval.rpoint[2];
	normal.normalize();
	// 将窗口角点从WCS转换到ECS
	struct resbuf rbFrom, rbTo;
	rbFrom.restype = RTSHORT;
	rbFrom.resval.rint = 0; // WCS 
	rbTo.restype = RT3DPOINT;
	rbTo.resval.rpoint[0] = normal[0];
	rbTo.resval.rpoint[1] = normal[1];
	rbTo.resval.rpoint[2] = normal[2];
	acedTrans(pt1, &rbFrom, &rbTo, FALSE, pt1);
	acedTrans(pt2, &rbFrom, &rbTo, FALSE, pt2);
	// 创建空间过滤器
	AcGePoint2dArray array;
	array.append(AcGePoint2d(pt1[0], pt1[1]));
	array.append(AcGePoint2d(pt2[0], pt2[1]));
	AcDbSpatialFilter spatialFilter;
	spatialFilter.setDefinition(
		array,
		normal,
		pt1[Z],
		ACDB_INFINITE_XCLIP_DEPTH,
		-ACDB_INFINITE_XCLIP_DEPTH,
		Adesk::kTrue);
	AcDbLayerFilter layerFilter;
	layerFilter.add(LayId);
	layerFilter.add(_T("3"));
	Acad::ErrorStatus es;
	es = pDb->applyPartialOpenFilters(&spatialFilter, &layerFilter);
	if (es == Acad::eOk) { return true; }
	else { return false; }
	//if ((es == Acad::eOk) && pDb->isPartiallyOpened())
	//{
	//	pDb->closeInput(true);
	//	return true;
	//}
	//else { return false; }
}

